FROM golang:1.25-alpine AS builder

WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /eventlogger ./cmd/eventlogger/

FROM alpine:3.19

RUN apk --no-cache add ca-certificates
RUN addgroup -S app && adduser -S -g app app

USER app

COPY --from=builder /eventlogger /eventlogger

EXPOSE 8080

CMD ["/eventlogger"]
