FROM golang:1.25-alpine AS builder

RUN apk --no-cache add lksctp-tools-dev
RUN apk add --no-cache build-base
WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -ldflags="-s -w" -o /sctp-proxy ./cmd/sctp-proxy/

FROM alpine:3.19

RUN apk --no-cache add ca-certificates lksctp-tools
RUN addgroup -S app && adduser -S -g app app

USER app

COPY --from=builder /sctp-proxy /sctp-proxy

EXPOSE 38412/sctp

CMD ["/sctp-proxy"]
